// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEz010keKj8GB5EGrdDF_-6MBKhx4wXv0',
    appId: '1:67317803547:android:26240e5f911ffefc0f66be',
    messagingSenderId: '67317803547',
    projectId: 'live-hanium',
    storageBucket: 'live-hanium.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcaZPFhZWvsohjtjRLKot727PsyGAzHrg',
    appId: '1:67317803547:ios:cbe369ad3a0296650f66be',
    messagingSenderId: '67317803547',
    projectId: 'live-hanium',
    storageBucket: 'live-hanium.firebasestorage.app',
    iosBundleId: 'com.example.liveFrontend',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7ncJwDMK4TJyfLSwjpktzitp7VWagQfw',
    appId: '1:67317803547:web:90fbc3d8d26cc7e00f66be',
    messagingSenderId: '67317803547',
    projectId: 'live-hanium',
    authDomain: 'live-hanium.firebaseapp.com',
    storageBucket: 'live-hanium.firebasestorage.app',
    measurementId: 'G-0ZJT46LJ31',
  );

}